---
ABL1:
  ref: "chr9"
  start: 130714369
  end: 130854114
  cigar_in: "M1396[0-1][1-9]N"
  catg: "expr"

WT1:
  ref: "chr11"
  start: 32428042
  end: 32434722
  cigar_in: "M438N"
  catg: "expr"

PRAME:
  ref: "chr22"
  start: 22548424
  end: 22548559
  seq_in: "^CGT"
  catg: "expr"

NPM1_wt:
  ref: "chr5"
  start: 171407744
  end: 171410635
  cigar_out: "4I"
  catg: "expr"
  cigar_in: "[0-9]M2752N[0-9][0-9]M"
  pos: 1714077


NPM1_mutant:
  ref: "chr5"
  start: 171407744
  end: 171410635
  cigar_in: "[0-9]M2752N[0-9][0-9]M4I"
  catg: "expr"


PML-RARA_bcr1:
  ref1: "chr17"
  pos1: 40348315
  ref2: "chr15"
  pos2: 74033415
  catg: "fusion"
  r1:
    ref: "chr17"
    start: 40348316
    end: 40348396
  r2:
    ref: "chr15"
    start: 74033319
    end: 74033414


PML-RARA_bcr3:
  ref1: "chr17"
  pos1: 40348315
  ref2: "chr15"
  pos2: 74023409
  catg: "fusion"
  r1:
    ref: "chr17"
    start: 40348316
    end: 40348396
  r2:
    ref: "chr15"
    start: 74023343
    end: 74023408


RUNX1-RUNX1T1:
  ref1: "chr8"
  pos1: 92017364
  ref2: "chr21"
  pos2: 34859473
  catg: "fusion"
  r1:
    ref: "chr21"
    start: 34859474
    end: 34859556
  r2:
    ref: "chr8"
    start: 92017298
    end: 92017363


BCR-ABL1_p190:
  ref1: "chr9"
  pos1: 130854063
  ref2: "chr22"
  pos2: 23182240
  catg: "fusion"
  r1:
    ref: "chr22"
    start: 23182069
    end: 23182239
  r2:
    ref: "chr9"
    start: 130854064
    end: 130854114



BCR-ABL1_p210:
  ref1: "chr9"
  pos1: 130854063
  ref2: "chr22"
  pos2: 23290414
  catg: "fusion"
  r1:
    ref: "chr22"
    start: 23289558
    end: 23290413
  r2:
    ref: "chr9"
    start: 130854064
    end: 130854114


CBFB-MYH11:
  ref1: "chr16"
  pos1: 15721052
  ref2: "chr16"
  pos2: 67082309
  catg: "fusion"
  r1:
    ref: "chr16"
    start: 67066750
    end: 67082308
  r2:
    ref: "chr16"
    start: 15720994
    end: 15721051



CBFB-MYH11-rare:
  ref: "chr16"
  start: 15720994
  end: 15721051
  catg: "expr"
  seq: "TCTTCATCTCCTCCATCTGGGTCTCCAGGGCCCGCTTGGACTTCTCCAGCTCATGGAC"



scriptPath: #path to scripts folder
StarIndex: #path to star Index
jobs_out: "out"


list_of_genes: ['ABL1','WT1','PRAME','NPM1_wt','NPM1_mutant']
list_of_fusions: ['CBFB-MYH11','RUNX1-RUNX1T1','PML-RARA_bcr1','BCR-ABL1_p190','BCR-ABL1_p210']


